name: Pruebas Orange HRMDemo con Serenity BDD para varios exploradores usando Selenium Manager

on:
  push:
    branches:
      - main
      - master
    pull_request:
      branches:
        - main
        - master

    workflow_dispatch:
      inputs:
        ambiente:
          description: 'Ambiente de pruebas (ej. dev, qa, prod)'
          required: true
          default: 'qa'
        etiqueta_gradle:
          description: 'Etiquetas de Serenity a ejecutar (ej. @Regresion)'
          required: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Ejecutar Pruebas Serenity BDD
        run: ./gradlew clean test -Denvironment=edge

      - name: Cargar Reporte Serenity (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report-${{ github.sha }}
          path: target/site/serenity
          retention-days: 90
          
      - name: Generar Resumen de la Ejecución
        run: |
          echo "### ✅ Pruebas Ejecutadas con Éxito" >> $GITHUB_STEP_SUMMARY
          echo "El reporte de Serenity BDD se ha generado y está disponible como Artifact." >> $GITHUB_STEP_SUMMARY
          echo "Revisa el artifact 'serenity-report-${{ github.sha }}' para ver los detalles." >> $GITHUB_STEP_SUMMARY
